name: timeofftracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase SDK for Cloud Firestore and Authentication
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4

  # State management using Hooks Riverpod
  hooks_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2

  # Immutable data classes generator
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Google Sign-In SDK
  google_sign_in: ^6.0.2

  # Routing and navigation
  go_router: ^6.2.0

  # Splash screen
  flutter_native_splash: ^2.2.19

  # Form Validation
  validators: ^3.0.0

  # UI
  flutter_staggered_animations: ^1.1.1
  dotted_border: ^2.0.0+3
  google_fonts: ^4.0.3
  overlay_support: ^2.1.0

  # Localization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints for code quality analysis
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.1.6
  custom_lint: ^0.3.2

  # Code generation
  build_runner: ^2.3.3
  riverpod_generator: ^2.1.4
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  source_gen: ^1.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#F6F6F6"
  image: assets/images/logo_icon.png
  android: true
  ios: true
